include:
  # Включить шаблон CI для Gradle
  - project: 'rosreestr/bpm/ci-templates'
    ref: 'main'
    file: 'templates/Gradle.gitlab-ci.yaml'
  # Включить шаблон для проверок кода
  - project: 'rosreestr/bpm/ci-templates'
    ref: 'linter'
    file: 'templates/Prebuild.gitlab-ci.yaml'

stages:
  - Precheck
  - Build
  - Test
  - Publish_jar
  - Release
  - Create_image

commits-check:
  stage: Precheck
  extends: .commits-check
  only:
    - merge_requests

kdoc-check:
  stage: Precheck
  extends: .kdoc-check
  only:
    - merge_requests

performance-check:
  stage: Precheck
  extends: .performance-check
  only:
    - merge_requests

style-check:
  stage: Precheck
  extends: .style-check
  only:
    - merge_requests

coroutines-check:
  stage: Precheck
  extends: .coroutines-check
  only:
    - merge_requests

complexity-check:
  stage: Precheck
  extends: .complexity-check
  only:
    - merge_requests

potential-bugs-check:
  stage: Precheck
  extends: .potential-bugs-check
  only:
    - merge_requests

exceptions-check:
  stage: Precheck
  extends: .exceptions-check
  only:
    - merge_requests

naming-check:
  stage: Precheck
  extends: .naming-check
  only:
    - merge_requests

empty-blocks-check:
  stage: Precheck
  extends: .empty-blocks-check
  only:
    - merge_requests

#Автоматическая сборка
Build:
  variables:
    APPS_PATH: integration/external-task-client
  stage: Build
  extends: .build_template

# Тесты
test:
  stage: Test
  extends: .test_template

# Публикация Артифактов
publish-to-nexus:
  stage: Publish_jar
  needs:
    - test
  extends: .publish-to-nexus-template

# Выпуск релиза
create-release:
  stage: Release
  extends: .create_release_dependency_template
  dependencies: []